In [2]:
import numpy as np


In [20]:
x = np.array([2,5,6])
print(x)
print(x.shape)
b  = np.array([
    [1, 2, 3]
    [4, 6, 5]
])
print(b.shape)

[2 5 6]
(3,)


<>:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\window-10\AppData\Local\Temp\ipykernel_216\1005230642.py:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1, 2, 3]
C:\Users\window-10\AppData\Local\Temp\ipykernel_216\1005230642.py:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1, 2, 3]
C:\Users\window-10\AppData\Local\Temp\ipykernel_216\1005230642.py:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1, 2, 3]


TypeError: list indices must be integers or slices, not tuple

In [18]:
c = np.arange(1,10, .2) #start, end, step
print(c)
print(c.shape)
d = np.linspace(1,10, 45) #start, end, number of elements
print(d)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
(45,)
[ 1.          1.20454545  1.40909091  1.61363636  1.81818182  2.02272727
  2.22727273  2.43181818  2.63636364  2.84090909  3.04545455  3.25
  3.45454545  3.65909091  3.86363636  4.06818182  4.27272727  4.47727273
  4.68181818  4.88636364  5.09090909  5.29545455  5.5         5.70454545
  5.90909091  6.11363636  6.31818182  6.52272727  6.72727273  6.93181818
  7.13636364  7.34090909  7.54545455  7.75        7.95454545  8.15909091
  8.36363636  8.56818182  8.77272727  8.97727273  9.18181818  9.38636364
  9.59090909  9.79545455 10.        ]


In [21]:
print(c.ndim)

1


In [24]:
print(c.reshape(3,5,3))

[[[1.  1.2 1.4]
  [1.6 1.8 2. ]
  [2.2 2.4 2.6]
  [2.8 3.  3.2]
  [3.4 3.6 3.8]]

 [[4.  4.2 4.4]
  [4.6 4.8 5. ]
  [5.2 5.4 5.6]
  [5.8 6.  6.2]
  [6.4 6.6 6.8]]

 [[7.  7.2 7.4]
  [7.6 7.8 8. ]
  [8.2 8.4 8.6]
  [8.8 9.  9.2]
  [9.4 9.6 9.8]]]


In [30]:
np.random.randint(1, 1000, (1,3))

array([[488, 525, 113]])

In [40]:
np.random.randint(-999, 10, (1,3))

array([[-820, -758, -363]])

maths in numpy

In [42]:
x = np.array ([
    [2,3,4],
    [5,6,7]
])

y= np.array ([
    [1,2,3],
    [4,7,7]
])

In [43]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x ** y)
print(x % y)

[[ 3  5  7]
 [ 9 13 16]]
[[ 1  1  1]
 [ 1 -1 -2]]
[[ 2  6 12]
 [20 42 63]]
[[2.         1.5        1.33333333]
 [1.25       0.85714286 0.77777778]]
[[       2        9       64]
 [     625   279936 40353607]]
[[0 1 1]
 [1 6 7]]


In [45]:
print(x *2)
print(x /2)
print(x **2)
print(x % 2)

[[ 4  6  8]
 [10 12 14]]
[[1.  1.5 2. ]
 [2.5 3.  3.5]]
[[ 4  9 16]
 [25 36 49]]
[[0 1 0]
 [1 0 1]]


In [51]:
#matrix multiplication
print(x.dot(y.T))
print(np.matmul(x, y.T))
print(x @ y.T)

[[ 20  65]
 [ 38 125]]
[[ 20  65]
 [ 38 125]]
[[ 20  65]
 [ 38 125]]


In [52]:
# statistical functions
print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.mean())
print(x.std())
print(x.min())
print(x.max())
print(x.argmax())
print(x.argmin())

27
[ 7  9 11]
[ 9 18]
4.5
1.707825127659933
2
7
5
0
